### ISSUE TITLE
What does "publish" mean?

### ISSUE THREAD

**Issue by npch** [research-software/resosuma-data#3]
E.g. there are the following relationships:

- Research Software Engineers	publish	Publishers
- Research Software Engineers	publish	Code platforms
- Research Software Engineers	publish	Archival repositories

Does publish here mean specifically software artefacts, or is it the more generic publishing of any artefact? What does it mean for Research Software Engineer publish Publishers, rather than Research Software Engineer publish Research software or Research Software Engineer publish Journal / Conference?

**Comment by sdruskat** [comment]
"publish" in this context refers to the more generic publishing of artifacts.

I think we should discuss whether "publish" should be something different for these different activities. I talked about, e.g.,  software publication and whether putting your code on GitHub is "publication" with @danielskatz recently, and he said (and I agree) that this isn't publication per se. 

So perhaps `X publish with/at Publisher`, `RSE deposit Archival repositories`, `RSE make public Code platforms` is more suitable?

**Comment by danielskatz** [comment]
I'm very confused, in part because the graph is quite small :)
I think
``X publish software with Publisher`` and ``X deposit software on Code platforms`` make sense to me.  These are three-part sentences, not two-part.

**Comment by sdruskat** [comment]
Thanks Dan, I hope to have a zoomable, etc., online vis of the graph ready for WSSSPE :). Not in time for the paper though, which is due today...

So, `X` `publish software with` `Publisher` is agreed on I think. So is `X` `deposit software in` (is "in" correct here?) `Archival repositories`.

As for pushing code to code platforms, I feel that while "deposit" is semantically correct, it has a connotation of "final" that I think might confuse people. What about "push code to", "commit code to" (both too git-speak?) or "upload code to"?

**Comment by danielskatz** [comment]
maybe just ``use as a development platform`` ?

**Comment by sdruskat** [comment]
Sounds good. I guess precision is more important than brevity.

**Comment by sdruskat** [comment]
I'm working on resolving this and have made the following changes to the CSV locally:

1. `Research Software Engineers, publish, Publishers` is now `Research Software Engineers, publish software with, Publishers`
2. `Research Software Engineers, publish, Code platforms` is now `Research Software Engineers, use as a development platform, Code platforms`
3. `Research Software Engineers, publish, Archival repositories` is now `Research Software Engineers, deposit software in, Archival repositories`.

I think these reflect what we discussed.

In addition, I think that resolving `Researchers, publish, Publishers` to `Researchers, publish *software* with, Publishers` would also make sense in the context of #1, but would perhaps be a corner case, and could be said to be covered with `RSEs, publish software with, Publishers`: Publishing software in this way would be an RSE-specific activity, and `Researchers, are, RSEs` would cover this.

So I would say that `Researchers, publish, Publishers` should be removed from the model.

**Comment by npch** [comment]
Looks good to me - and agree with your way of resolving Research publish Publishers
