### ISSUE TITLE
Correct resolution for "People" > "disseminate" > "Publishers, repositories, indices"?

### ISSUE THREAD

**Issue by sdruskat** [research-software/resosuma-data#4]
@danielskatz: In your original sustainability schematic, you have the above relation. I'm wondering what, in resosouma-data, this would resolve to. I can see two options:

If "people" "disseminate" to "repositories", these people would be RSEs, and the current edge for resosume-data would be the existing "RSEs disseminate Archival repositories" (perhaps I should add a "with" to the verb).

If "people" "disseminate" to "indices", these people wouldn't be RSEs, and we would have to either add a role for people that do that, and I don't know that they exist.  
Or "disseminate" would be an edge going from, e.g., "Archival repositories" to "Indices".

Can you explain please? Thanks.

**Comment by sdruskat** [comment]
On second thoughts on what "disseminate" in this case actually means, if you mean a "secondary" publishing process, e.g., as for publishing *preprints* in addition to publishing with a "Publisher", both "Researchers" and "RSEs" "disseminate to" "Archival repos" would make sense...

**Comment by danielskatz** [comment]
You may be assuming too much intent on my part in the original idea.  I *think* I mean that after people (like RSEs) write software, they should publish it somewhere.  I added indices because there were papers that discussed the whole archiving and indexing process.

**Comment by sdruskat** [comment]
Thanks Dan. That makes it sufficiently clear to me. I'll check if the model has to be changed based on this.

**Comment by sdruskat** [comment]
I think the "dissemination" process as used by RSEs is now covered in "Research Software Engineers, deposit software in, Archival repositories", so I'll remove the "disseminate" action from "RSEs".

I'll also remove the same action from "Resesarcher" for the reasons discussed in https://github.com/research-software/resosuma-data/issues/3#issuecomment-433712147.

As for the indexing process, this is covered from the other direction by "Indexers, index, Research software".
